# Generated by Django 5.0.6 on 2024-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gif_offer/')),
                ('big_image', models.ImageField(upload_to='big_offer_image/')),
                ('marquee', models.CharField(max_length=100)),
            ],
        ),
    ]
