# Generated by Django 5.0.6 on 2024-09-13 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvs_app', '0004_category_cid_product_date_product_image_product_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='jvs_app.product'),
        ),
    ]
