# Generated by Django 5.0.6 on 2024-09-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvs_app', '0005_alter_productimages_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='offer.jpg', upload_to='offer_multi_images/')),
                ('Offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='jvs_app.offer')),
            ],
        ),
    ]
